### PR TITLE
Issue with multiple calls to the contract

### PR DESCRIPTION
**Pull request by dabana**
An event is created in the contract to log to the blockchain:
1) Winner address
2) Loser address
3) a game index
4) the bet ammount

An array containing the players address, *playerAddresses*, has been created for this purpose. But the React app seams to be calling its *SendWinner()* multiple times in a row. This creates an opcode error in the VM because the extra calls to the contract function *ClaimBet()* cause an indexing of an empty array (*playerAddresses* is empty when the game is finished and the bet is claimed by the winner).

It is a React related issues I have problems solving.

### CODE REVIEW

**Comment by AkaashMukherjee** [comment]
I get:

Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

**Comment by dabana** [comment]
Oui ça c'est un warning parce qu'on change le state du React component dans le *render()*. Ça cause pas de problème, mais après il est supposé y avoir une autre erreur VM invalid op code

**Comment by dabana** [comment]
Uncaught (in promise) Error: Returned error: VM Exception while processing transaction: invalid opcode

**Comment by dabana** [comment]
Je pense que je sais c'est quoi le problème. C'Est que le remet pas les boolean de mon mapping a false dans *ClaimBet()*.

Mais ça regle pas les calls multiples à *SendWinner()* mais c'est peut-être pas grave

**Comment by dabana** [comment]
Ah ah! c'est le require qui envoie l'erreur. Bien sur!  

https://medium.com/blockchannel/the-use-of-revert-assert-and-require-in-solidity-and-the-new-revert-opcode-in-the-evm-1a3a7990e06e

**Comment by dabana** [comment]
Okai je n'ai plus l'erreur quand je commente la ligne 
*require(isPlayer[msg.sender]);* 
ET la ligne 
*delete playerAddresses;* 
dans le contract.

**Comment by dabana** [comment]
Mais tout ça viens du call multiple a *SendWinner()*

**Pull request merged**
